"""empty message

Revision ID: 50617fbc2a48
Revises: b8ea423636ae
Create Date: 2024-04-26 15:46:25.018648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50617fbc2a48'
down_revision = 'b8ea423636ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
